# permissions for end users to edit curatorconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: curatorconfig-editor-role
rules:
- apiGroups:
  - curator.operatorfirst.io
  resources:
  - curatorconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - curator.operatorfirst.io
  resources:
  - curatorconfigs/status
  verbs:
  - get
