# permissions for end users to view curatorconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: curatorconfig-viewer-role
rules:
- apiGroups:
  - curator.operatorfirst.io
  resources:
  - curatorconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - curator.operatorfirst.io
  resources:
  - curatorconfigs/status
  verbs:
  - get
