apiVersion: v1
kind: Secret
metadata:
  name: db-secret-file
type: Opaque
data:
  DatabaseUser: <database-user-name>
  DatabasePassword: <database-password>
  DatabasePort: <database-port>
  DatabaseHostName: <<database-host-name>
  DatabaseName: <database-name>
