name: ci
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
    - main
jobs:
  test:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ~1.17
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Cache go module cache
      id: cache-go-mod
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: go mod download

    - name: Verify manifests
      run: make manifests && make generate && git diff --exit-code

    - name: Verify Go dependencies
      run: go mod tidy && git diff --exit-code

    - name: Run tests
      run: make test

    - name: Verify binary can compile
      run: make build
